/*!
 * Enquiry forms, waterautomation.com.
 * GENERATED by tools/forms-wire.mjs (formsJs); edit it there, not here.
 * Posts the form by fetch and answers in place, as Elementor Pro's form
 * handler did. Without it the form still posts and lands on /thank-you/.
 */
(function () {
  'use strict';

  var ENDPOINT = "/_forms/submit.php";
  var FAILED = "Your submission failed because of an error.<br>Please email us at <a href=\"mailto:support@waterautomation.com\">support@waterautomation.com</a> and we will pick it up from there.";
  var SPINNER = '<i class="fa fa-spinner fa-spin"></i>&nbsp;';

  if (!window.fetch || !window.FormData || !document.querySelectorAll) {
    return;
  }

  function each(list, fn) {
    Array.prototype.forEach.call(list, fn);
  }

  function drop(el) {
    if (el && el.parentNode) {
      el.parentNode.removeChild(el);
    }
  }

  // Elementor announced these as jQuery events on the form.
  function announce(form, name, data) {
    var $ = window.jQuery;
    if (typeof $ === 'function') {
      try {
        $(form).trigger(name, data === undefined ? [] : [data]);
      } catch (e) { /* a listener's failure is not the form's */ }
    }
  }

  function svgIcons() {
    var c = window.elementorFrontendConfig;
    return !!(c && c.experimentalFeatures && c.experimentalFeatures.e_font_icon_svg);
  }

  function inputsOf(el) {
    return el.querySelectorAll('input, select, textarea, button');
  }

  function note(form, className, html) {
    var div = document.createElement('div');
    div.className = className;
    div.setAttribute('role', 'alert');
    div.innerHTML = html;
    form.appendChild(div);
  }

  function beforeSend(form, buttons) {
    form.style.transition = 'opacity 500ms';
    form.style.opacity = '0.45';
    form.classList.add('elementor-form-waiting');
    each(form.querySelectorAll('.elementor-message'), drop);
    each(form.querySelectorAll('.elementor-error'), function (el) {
      el.classList.remove('elementor-error');
    });
    each(form.querySelectorAll('div.elementor-field-group'), function (group) {
      group.classList.remove('error');
      each(group.querySelectorAll('span.elementor-form-help-inline'), drop);
      each(inputsOf(group), function (i) {
        i.setAttribute('aria-invalid', 'false');
      });
    });
    each(buttons, function (button) {
      button.setAttribute('disabled', 'disabled');
      each(button.children, function (child) {
        if (child.tagName === 'SPAN') {
          var spin = document.createElement('span');
          spin.className = 'elementor-button-text elementor-form-spinner';
          spin.innerHTML = SPINNER;
          child.insertBefore(spin, child.firstChild);
        }
      });
    });
  }

  function settle(form, buttons) {
    each(buttons, function (button) {
      button.removeAttribute('disabled');
      each(button.querySelectorAll('.elementor-form-spinner'), drop);
    });
    form.style.transition = 'opacity 100ms';
    form.style.opacity = '1';
    form.classList.remove('elementor-form-waiting');
  }

  function answered(form, buttons, res) {
    settle(form, buttons);
    if (res && res.success) {
      announce(form, 'submit_success', res);
      announce(form, 'form_destruct', res);
      form.reset();
      if (res.message) {
        note(form, 'elementor-message elementor-message-success' + (svgIcons() ? ' elementor-message-svg' : ''), res.message);
      }
      return;
    }
    var errors = res && res.errors;
    if (errors && typeof errors === 'object') {
      Object.keys(errors).forEach(function (id) {
        var field = form.querySelector('[id="form-field-' + String(id).replace(/[^A-Za-z0-9_-]/g, '') + '"]');
        var group = field && field.parentNode;
        if (!group) {
          return;
        }
        group.classList.add('elementor-error');
        var span = document.createElement('span');
        span.className = 'elementor-message elementor-message-danger elementor-help-inline elementor-form-help-inline';
        span.setAttribute('role', 'alert');
        span.innerHTML = errors[id];
        group.appendChild(span);
        each(inputsOf(group), function (i) {
          i.setAttribute('aria-invalid', 'true');
        });
      });
      announce(form, 'error');
    }
    note(form, 'elementor-message elementor-message-danger', (res && res.message) || FAILED);
  }

  function failed(form, buttons) {
    note(form, 'elementor-message elementor-message-danger', FAILED);
    settle(form, buttons);
    announce(form, 'error');
  }

  function bind(form) {
    if (form.getAttribute('data-wa-ajax') === '1') {
      return;
    }
    form.setAttribute('data-wa-ajax', '1');
    form.addEventListener('submit', function (event) {
      if (event.defaultPrevented) {
        return;
      }
      event.preventDefault();
      if (form.classList.contains('elementor-form-waiting')) {
        return;
      }
      var buttons = form.querySelectorAll('[type="submit"]');
      var data = new FormData(form);
      beforeSend(form, buttons);
      window.fetch(ENDPOINT, {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
        headers: { Accept: 'application/json' }
      }).then(function (response) {
        return response.json();
      }).then(function (res) {
        answered(form, buttons, res);
      }, function () {
        failed(form, buttons);
      });
    });
  }

  function init() {
    each(document.querySelectorAll('form[action="' + ENDPOINT + '"]'), bind);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
