<?php
/**
 * Form handler for the static build of waterautomation.com.
 *
 * GENERATED by tools/forms-wire.mjs. Do not edit this file -- edit submitPhp()
 * in that tool and re-run it, or the next run overwrites what you wrote.
 *
 * THIS FILE NEEDS A HOST THAT RUNS PHP. On Netlify, Cloudflare Pages, GitHub
 * Pages or any other pure-static host it is not executed, and every form on the
 * site posts into nothing. See
 * SEO Program/plans/water-automation/switchover-preflight.md.
 *
 * Every enquiry form on the site posts here: tools/forms-wire.mjs sets
 * action="/_forms/submit.php" on each one and renames the Elementor widget hook
 * that would otherwise have JavaScript intercept the submit and send it to
 * WordPress's admin-ajax.php, which does not exist on a static host.
 *
 * What happens to a submission, in order:
 *   1. A filled spam trap gets the success answer and nothing is sent. It is
 *      noted in private/spam-YYYY-MM.jsonl, so a real person caught by it
 *      can still be found.
 *   2. It must carry an email address or a phone number, and a well-formed
 *      email if it has one.
 *   3. It is written to private/submissions-YYYY-MM.jsonl, outside the web
 *      root, BEFORE any email is attempted.
 *   4. wa_deliver() (_lib/wa.php) sends it: Resend, Microsoft Graph, SMTP,
 *      then mail(), in the order the private config gives.
 *   5. The outcome is appended to the same log under the same id.
 *   6. The answer: JSON {success, message} to /_forms/forms.js, which shows it
 *      in place under the form the way Elementor did; to a browser posting
 *      the form itself, a 303 to /thank-you/ or the failure page.
 *
 * The private config is dirname(public_html)/private/config.php; see
 * tools/config.example.php. With none at all, step 4 is the plain mail() this
 * handler always used and step 3 still happens if PHP can create that folder.
 */

// Never show a PHP notice to a visitor; the host's error log is where they go.
ini_set('display_errors', '0');
error_reporting(E_ALL);

// UTC, and labelled as UTC in the mail. This business publishes no address and
// no phone number anywhere on its site, so its local time is not something this
// file is in a position to know.
date_default_timezone_set('UTC');

require_once __DIR__ . '/../_lib/wa.php';

// Where enquiries go when the private config names nowhere else (forms.to, or
// forms.to_by_form keyed by form_id), and the address a visitor is given when
// sending fails.
$TO = 'support@waterautomation.com';
$FROM_NAME = 'Water Automation website';
$THANKS = '/thank-you/';
$CONTACT = 'support@waterautomation.com';

// form_id -> the button's own words, the hidden spam-trap fields, and every
// visible field under the label the page puts above it. Harvested from the
// pages themselves at build time, so it cannot drift from what was shipped.
$FORMS = [
    '4016f62' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    '53ba0a2' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    '66e5502' => ['label' => 'Submit', 'honeypots' => ['field_f6ed4c3'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'consent' => 'I Authorize Water Automation']],
    '6f38a5b5' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    'a69a1db' => ['label' => 'Request a call', 'honeypots' => [], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    'b7b7273' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    'c847ee0' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    'd0d16b3' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'job_title' => 'Job Title', 'company' => 'Company Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    'd53150b' => ['label' => 'Request a call', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
    'f070572' => ['label' => 'Become a Partner', 'honeypots' => ['hpot'], 'fields' => ['name' => 'Name', 'job_title' => 'Job Title', 'company' => 'Company Name', 'email' => 'E-mail', 'tel' => 'Tel', 'message' => 'Message']],
];

// What the visitor is told, in Elementor Pro's own default words (see
// tools/forms-messages.mjs). HTML, as Elementor's were.
$MESSAGES = ['success' => 'Your submission was successful.', 'error' => 'Your submission failed because of an error.', 'required' => 'This field is required.', 'server' => 'Your submission failed because of a server error.', 'badEmail' => 'That email address did not look right.', 'contact' => 'Please email us at <a href="mailto:support@waterautomation.com">support@waterautomation.com</a> and we will pick it up from there.'];

// Posted with every form and never worth repeating in the email: Elementor's
// plumbing, and the page stamp, which is reported once at the foot instead.
$MACHINE = ['post_id', 'form_id', 'queried_id', 'referer_title', 'action',
  'g-recaptcha-response', 'wa_page'];

// Elementor posted by AJAX and answered in place; /_forms/forms.js does the
// same and asks for JSON. A browser posting the form itself asks for HTML.
$WANTS_JSON = isset($_SERVER['HTTP_ACCEPT']) && is_string($_SERVER['HTTP_ACCEPT'])
    && stripos($_SERVER['HTTP_ACCEPT'], 'application/json') !== false;

/**
 * A path on this site, or null. Everything that reaches a Location header goes
 * through here first: an absolute URL, a protocol-relative "//elsewhere" or a
 * header-splitting newline is refused outright rather than cleaned up, because
 * a redirector that tries to repair hostile input is how open redirects happen.
 */
function wa_local_path($url) {
    if (!is_string($url) || $url === '') {
        return null;
    }
    $path = parse_url($url, PHP_URL_PATH);
    if (!is_string($path) || $path === '' || $path[0] !== '/' || substr($path, 0, 2) === '//') {
        return null;
    }
    if (preg_match('#[^A-Za-z0-9/_.~%:@!$&()*+,;=-]#', $path)) {
        return null;
    }
    return $path;
}

/**
 * The page the visitor was on. HTTP_REFERER first, because it is the browser's
 * own answer; the wa_page field that tools/forms-wire.mjs stamps into the
 * markup is the fallback for the browsers and privacy settings that send no
 * referer at all.
 */
function wa_page() {
    $host = isset($_SERVER['HTTP_HOST']) ? preg_replace('/:\d+$/', '', $_SERVER['HTTP_HOST']) : '';
    $ref = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
    if (is_string($ref) && $ref !== '') {
        $parts = parse_url($ref);
        $refHost = (is_array($parts) && isset($parts['host'])) ? $parts['host'] : '';
        if ($refHost === '' || ($host !== '' && strcasecmp($refHost, $host) === 0)) {
            $path = wa_local_path($ref);
            if ($path !== null) {
                return $path;
            }
        }
    }
    // The stamped field is a bare path and nothing else, so a value carrying a
    // scheme or a host did not come from the markup and is not trusted to name
    // the page. Refused rather than reduced to its path: a
    // "//elsewhere.example/contact-us/" would otherwise pass as "/contact-us/".
    $raw = isset($_POST['wa_page']) ? $_POST['wa_page'] : '';
    if (is_string($raw) && $raw !== '' && $raw[0] === '/' && substr($raw, 0, 2) !== '//') {
        $stamped = wa_local_path($raw);
        if ($stamped !== null) {
            return $stamped;
        }
    }
    return '/';
}

/** 303, so the browser turns the POST into a GET and a refresh cannot resubmit. */
function wa_redirect($path) {
    header('Cache-Control: no-store');
    header('Location: ' . $path, true, 303);
    exit;
}

/** A JSON answer for /_forms/forms.js. */
function wa_json($status, array $payload) {
    http_response_code($status);
    header('Cache-Control: no-store');
    header('Content-Type: application/json; charset=UTF-8');
    header('X-Content-Type-Options: nosniff');
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE);
    exit;
}

/** Success: Elementor's message in place for the script, /thank-you/ for a plain post. */
function wa_succeed() {
    global $WANTS_JSON, $THANKS, $MESSAGES;
    if ($WANTS_JSON) {
        wa_json(200, ['success' => true, 'message' => $MESSAGES['success']]);
    }
    wa_redirect($THANKS);
}

/**
 * The failure answer.
 *
 * To the script: JSON with success false, the message it shows under the form,
 * and any per-field messages, shaped as Elementor's were so the same markup
 * appears. The fields keep what the visitor typed; only success clears them.
 *
 * To a plain post: a page, not a redirect. The whole point of this handler is
 * that an enquiry never disappears without anyone noticing, so say it plainly,
 * give them the address that does work, and leave the back button holding
 * everything they typed.
 */
function wa_fail($code, $headline, $detail, $message = null, array $errors = []) {
    global $CONTACT, $WANTS_JSON, $MESSAGES;
    if ($WANTS_JSON) {
        $out = ['success' => false, 'message' => ($message !== null) ? $message : $MESSAGES['error']];
        if ($errors) {
            $out['errors'] = $errors;
        }
        wa_json($code, $out);
    }
    http_response_code($code);
    header('Cache-Control: no-store');
    header('Content-Type: text/html; charset=UTF-8');
    $h = htmlspecialchars($headline, ENT_QUOTES, 'UTF-8');
    $d = htmlspecialchars($detail, ENT_QUOTES, 'UTF-8');
    $c = htmlspecialchars($CONTACT, ENT_QUOTES, 'UTF-8');
    // No "go back" link on this page: the only way to write one is a
    // javascript: href, which a content-security policy is entitled to block,
    // and a link that may do nothing is worse than a sentence that always does.
    echo '<!doctype html><html lang="en"><head><meta charset="utf-8">'
       . '<meta name="viewport" content="width=device-width, initial-scale=1">'
       . '<meta name="robots" content="noindex">'
       . '<title>' . $h . ' | Water Automation</title>'
       . '<style>body{margin:0;background:#f4f7f9;color:#12303f;'
       . 'font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}'
       . 'main{max-width:34rem;margin:12vh auto;padding:2rem;background:#fff;border-radius:12px;'
       . 'box-shadow:0 2px 18px rgba(18,48,63,.09)}h1{font-size:1.5rem;margin:0 0 1rem}'
       . 'a{color:#0d6e9e}p{margin:0 0 1rem}</style></head><body><main>'
       . '<h1>' . $h . '</h1><p>' . $d . '</p>'
       . '<p>Please email us at <a href="mailto:' . $c . '">' . $c . '</a> and we will pick it up from there.</p>'
       . '<p>Your browser\'s back button will take you to the form with everything '
       . 'you typed still in it. <a href="/">Back to the homepage</a></p>'
       . '</main></body></html>';
    exit;
}

/** Multi-line text with the control characters and the stray carriage returns taken out. */
function wa_text($value) {
    if (!is_string($value)) {
        return '';
    }
    $value = str_replace(["\0", "\r\n", "\r"], ['', "\n", "\n"], $value);
    $value = preg_replace('/[\x01-\x08\x0B\x0C\x0E-\x1F\x7F]/', '', $value);
    return trim($value);
}

/** One line of text. Also what makes a value safe to put in a mail header. */
function wa_line($value) {
    return trim(str_replace("\n", ' ', wa_text($value)));
}

/** Cut to a byte length without splitting a UTF-8 character in half. */
function wa_cut($value, $max) {
    if (strlen($value) <= $max) {
        return $value;
    }
    if (function_exists('mb_substr')) {
        return mb_substr($value, 0, $max, 'UTF-8');
    }
    return preg_replace('/[\x80-\xBF]*$/', '', substr($value, 0, $max));
}

/**
 * Who this form's enquiries go to: forms.to_by_form[form_id], else forms.to,
 * else support@waterautomation.com. Each may be one address or a list. A configured value with no
 * valid address in it falls back to support@waterautomation.com rather than sending to no one.
 */
function wa_form_recipients($formId) {
    global $TO;
    $want = null;
    $byForm = wa_cfg('forms.to_by_form');
    if ($formId !== '' && is_array($byForm) && array_key_exists($formId, $byForm)) {
        $want = $byForm[$formId];
    }
    if ($want === null) {
        $want = wa_cfg('forms.to');
    }
    $list = [];
    foreach ((array) $want as $addr) {
        if (is_string($addr) && filter_var(trim($addr), FILTER_VALIDATE_EMAIL) !== false) {
            $list[] = trim($addr);
        }
    }
    if (!$list) {
        if ($want !== null) {
            error_log('wa-forms: forms.to / forms.to_by_form holds no valid address for form ' . $formId . '; using ' . $TO);
        }
        $list = [$TO];
    }
    return $list;
}

/**
 * A spam-trap hit, noted so a real person caught by it can be found, and
 * capped at 20 MB a month so a bot flood cannot fill the disk.
 */
function wa_log_spam(array $record) {
    $dir = wa_private_dir();
    if ($dir === null) {
        return;
    }
    $file = $dir . '/spam-' . gmdate('Y-m') . '.jsonl';
    clearstatcache(true, $file);
    if (is_file($file) && filesize($file) > 20 * 1024 * 1024) {
        return;
    }
    wa_log_append('spam', $record);
}

/* ------------------------------------------------------------------------ */

if (!isset($_SERVER['REQUEST_METHOD']) || strtoupper($_SERVER['REQUEST_METHOD']) !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    header('Content-Type: text/plain; charset=UTF-8');
    echo "This address accepts form submissions only.\n";
    exit;
}

$page = wa_page();
$ip = wa_client_ip();
$agent = wa_cut(wa_line(isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : ''), 400);

// A post larger than the host's post_max_size arrives with $_POST emptied and
// no warning of its own. Say so here rather than letting it fall through and
// look like an empty form.
if (empty($_POST) && isset($_SERVER['CONTENT_LENGTH']) && (int) $_SERVER['CONTENT_LENGTH'] > 0) {
    wa_fail(413, 'That message was too long to send',
        'The server would not accept a message that size, so it has not reached us.',
        $MESSAGES['error'] . '<br>' . $MESSAGES['contact']);
}

$posted = (isset($_POST['form_fields']) && is_array($_POST['form_fields'])) ? $_POST['form_fields'] : [];

$formId = preg_replace('/[^0-9a-z]/', '', strtolower(wa_line(isset($_POST['form_id']) ? $_POST['form_id'] : '')));
$known = isset($FORMS[$formId]) ? $FORMS[$formId] : null;

// The bot trap, before any validation. A filled-in honeypot gets the same
// answer a real submission gets, so nothing is learned from the difference.
// Which field is the trap is per-form, so an unrecognised form_id falls back to
// checking every trap name any form on this site uses.
$traps = ($known !== null) ? $known['honeypots'] : [];
if ($known === null) {
    foreach ($FORMS as $f) {
        foreach ($f['honeypots'] as $t) {
            $traps[] = $t;
        }
    }
}
foreach ($traps as $trap) {
    if (isset($posted[$trap]) && is_string($posted[$trap]) && wa_line($posted[$trap]) !== '') {
        $caught = [];
        foreach ($posted as $k => $v) {
            if (is_string($k) && is_string($v) && $v !== '') {
                $caught[$k] = wa_cut(wa_text($v), 500);
            }
        }
        wa_log_spam(['type' => 'honeypot', 'form' => $formId, 'page' => $page, 'trap' => $trap,
            'ip' => $ip, 'user_agent' => $agent, 'fields' => $caught]);
        wa_succeed();
    }
}

$name = wa_cut(wa_line(isset($posted['name']) ? $posted['name'] : ''), 200);
$email = wa_cut(wa_line(isset($posted['email']) ? $posted['email'] : ''), 250);
$tel = wa_cut(wa_line(isset($posted['tel']) ? $posted['tel'] : ''), 200);

// One way to answer, and no more than the form itself asks for. Every one of
// the ten forms marks its email field required; nothing else on any of them is
// worth turning a person away over, so nothing else is checked here.
if ($email === '' && $tel === '') {
    wa_fail(400, 'We need a way to reply',
        'The message arrived without an email address or a phone number, so there is no way to answer it.',
        $MESSAGES['error'], ['email' => $MESSAGES['required']]);
}
if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    wa_fail(400, 'That email address did not look right',
        'The message has not been sent, because the address on it would bounce.',
        $MESSAGES['error'], ['email' => $MESSAGES['badEmail']]);
}

$label = ($known !== null && $known['label'] !== '') ? $known['label'] : 'Website form';
$label = substr(preg_replace('/\s+/', ' ', preg_replace('/[^A-Za-z0-9 &\/\x27-]/', '', $label)), 0, 40);
if (trim($label) === '') {
    $label = 'Website form';
}

/* ---------------------------------------------------------------- the body */

$inline = [];
$blocks = [];
$seen = [];
$fieldLabels = ($known !== null) ? $known['fields'] : [];

// The form's own fields first, in the order the page lays them out, under the
// label the page puts above them.
foreach ($fieldLabels as $field => $fieldLabel) {
    $seen[$field] = true;
    if (!isset($posted[$field]) || !is_string($posted[$field])) {
        continue;
    }
    $value = wa_cut(wa_text($posted[$field]), 20000);
    if ($value === '') {
        continue;
    }
    $shown = ($fieldLabel !== '') ? $fieldLabel : $field;
    if (strpos($value, "\n") === false) {
        $inline[] = [$shown, $value];
    } else {
        $blocks[] = [$shown, $value];
    }
}

// Anything a form grows later still reaches the inbox, under its own name --
// except the traps, which are never repeated back.
foreach ($posted as $field => $value) {
    if (isset($seen[$field]) || !is_string($field) || !is_string($value)) {
        continue;
    }
    if (in_array($field, $traps, true)) {
        continue;
    }
    $value = wa_cut(wa_text($value), 20000);
    if ($value === '') {
        continue;
    }
    if (strpos($value, "\n") === false) {
        $inline[] = [$field, $value];
    } else {
        $blocks[] = [$field, $value];
    }
}

foreach ($_POST as $field => $value) {
    if ($field === 'form_fields' || !is_string($field) || !is_string($value)) {
        continue;
    }
    if (in_array($field, $MACHINE, true)) {
        continue;
    }
    $value = wa_cut(wa_text($value), 20000);
    if ($value !== '' && strpos($value, "\n") === false) {
        $inline[] = [$field, $value];
    }
}

/* ---------------------------------------------------------------- the mail */

// One id for the log line, the delivery line and the email, so each can be
// found from the others.
$id = gmdate('Ymd\THis\Z') . '-' . bin2hex(random_bytes(5));

$width = 0;
foreach ($inline as $row) {
    $width = max($width, strlen($row[0]));
}
$width = max($width, 9);

$body = 'New ' . $label . ' submission from ' . $page . "\n\n";
foreach ($inline as $row) {
    $body .= str_pad($row[0] . ':', $width + 2) . $row[1] . "\n";
}
foreach ($blocks as $row) {
    $body .= "\n" . $row[0] . "\n" . str_repeat('-', strlen($row[0])) . "\n" . $row[1] . "\n";
}
$body .= "\n" . str_repeat('-', 40) . "\n";
$body .= str_pad('Page:', $width + 2) . $page . "\n";
$body .= str_pad('Form:', $width + 2) . ($formId !== '' ? $formId : 'unknown') . "\n";
$body .= str_pad('Received:', $width + 2) . date('Y-m-d H:i:s T') . "\n";
if ($ip !== '') {
    $body .= str_pad('From IP:', $width + 2) . $ip . "\n";
}
$body .= str_pad('Ref:', $width + 2) . $id . "\n";

$subject = wa_line('Water Automation: ' . $label . ' from ' . $page);
$to = wa_form_recipients($formId);

// On disk first. If every transport below fails, the enquiry is still here.
$fields = [];
foreach ($posted as $k => $v) {
    if (is_string($k) && is_string($v) && !in_array($k, $traps, true)) {
        $fields[$k] = wa_cut(wa_text($v), 20000);
    }
}
$logged = wa_log_append('submissions', [
    'type' => 'submission', 'id' => $id, 'form' => ($formId !== '' ? $formId : 'unknown'), 'label' => $label,
    'page' => $page, 'to' => $to, 'ip' => $ip, 'user_agent' => $agent, 'fields' => $fields,
    'subject' => $subject, 'text' => $body,
]);
if (!$logged) {
    error_log('wa-forms: ' . $id . ' could not be written to the submissions log; sending anyway');
}

$result = wa_deliver([
    'id' => $id,
    'to' => $to,
    'subject' => $subject,
    'text' => $body,
    // So hitting reply answers the person who filled the form in.
    'reply_to' => $email,
    'from_name' => $FROM_NAME,
]);

wa_log_append('submissions', [
    'type' => 'delivery', 'id' => $id, 'ok' => $result['ok'], 'transport' => $result['transport'],
    'errors' => $result['errors'], 'skipped' => isset($result['skipped']) ? $result['skipped'] : [],
    'logged' => $logged,
]);

if (!$result['ok']) {
    wa_fail(500, 'We could not send that message',
        'Something went wrong on our side and your message did not reach us. Nothing you typed has been lost -- go back and it will still be there.',
        $MESSAGES['server'] . '<br>' . $MESSAGES['contact']);
}

wa_succeed();
